### ISSUE TITLE
Request: mutation on collections

### ISSUE THREAD

**Issue by pmatos** [lexi-lambda/racket-collections#15]
Can we have an extension to the collections package, which adds mutable-collections in which we have `set-nth!` and `set-nth*!`? Or is there a reason why these were not added in the first place?

**Comment by lexi-lambda** [comment]
I don’t think so. The collections library makes various assumptions that collections are immutable, which allows the system to avoid copying when performing functional updates, and it makes it possible for things to be lazier. Laziness doesn’t work when a collection is mutable, since by the time the collection is actually consulted, its values might have been changed.

**Comment by pmatos** [comment]
Understood. I am curious about what you mean about: 

> avoid copying when performing functional updates

Can you point me to code doing this please?

**Comment by lexi-lambda** [comment]
Sure. One of the most obvious places is [`data/collection/private/random-access`](https://github.com/lexi-lambda/racket-collections/blob/5b3ec9b3ea3ca493f3fcda4994b81bc804f29870/collections-lib/data/collection/private/random-access.rkt), which provides an implementation of `reverse` that simply redirects accesses without actually realizing an entirely new data structure. Other examples are more standard, though, and they mostly involve the choice to use lazy streaming pervasively.

**Comment by pmatos** [comment]
Nice, that's very interesting how you implemented reverse! :+1:
