### ISSUE TITLE
set-nth* guarantees

### ISSUE THREAD

**Issue by pmatos** [lexi-lambda/racket-collections#16]
Is there any guarantee that `set-nth*` will not create intermediate copies of the sequence? The documentation says it calls `set-nth` repeatedly but that means it'll probably copy the original sequence once per set tuple, right?

**Comment by lexi-lambda** [comment]
Yes, that’s right. It would be possible to make `set-nth*` a part of the interface so that individual data structures could provide more efficient implementations, but the default implementation would still call `set-nth` multiple times. Still, even the naïve implementation is useful with persistent data structures, which provide efficient functional updates. For an integer-indexed data structure of the sort `set-nth` is useful with, this library is intended to be used with its companion, [`data/pvector`](http://docs.racket-lang.org/pvector/index.html), which provides a persistent vector with an efficient `set-nth` implementation.

**Comment by pmatos** [comment]
OK, understood. Thanks.
